{FILTRO_MODAL}

{MODAL_EXCLUIR}

<body>
    <div id="wrapper">
        <div id="page-wrapper">
            <div class="container-fluid">
                <div class="row">
                    <div class="col-lg-12">
                        <p>  </p>


                        
                        {ALERTA}

                        {BREADCRUMBS}

                        <div class="panel panel-default">
                            <div class="panel-heading clearfix">                            
                                <a class="btn btn-success pull-right" href="{LINK_INCLUIR}">Incluir</a>
                                <button type="button" class="btn btn-info pull-right" style="margin-right: 5px;" 
                                        data-toggle="modal" data-target="#myModal">Filtrar</button>
                                <h3 class="panel-title" style="padding-top: 7.5px;"><strong>{NOME_LISTA}</strong></h3>
                            </div>                           
                        <div class="panel-body">
                        <div class="dataTable_wrapper">
                        <table class="table table-striped table-bordered table-hover table-condensed" id="tabela">
                        <thead>
                            {TABELA_TITULOS}
                        </thead>
                        <tbody> 
                            <!-- BEGIN BLOCK_REGISTROS -->
                            <tr>
                                {TABELA_CAMPOS}
                                <td>
                                    <a class="btn btn-warning btn-xs" href="{LINK_EDITAR}">Editar</a>
                                    <a class="btn btn-warning btn-xs" name="teste[]" id="{REG_ID}" url="{LINK_EDITAR}" href="#">Teste</a>
                                    <a href="#" class="confirm-delete btn btn-danger btn-xs" data-href="{LINK_EXCLUIR}" data-toggle="modal" data-target="#confirm-delete" data-id="{REG_ID}">Excluir</a>
                                </td>
                            </tr>           
                            <!-- END BLOCK_REGISTROS -->
                        </tbody>    
                        </table>
                        </div>
                        </div>
                        </div>                        
                    </div>
                </div>                
            </div>            
        </div>        
    </div>    
</body>

<script>
    $(document).ready(function() {
        $('#tabela').DataTable({
            responsive: true,
            "language": {"url": "/TESTE/public/pt-br.json"},
            "pagingType": "full_numbers",//, "displayStart": 0            
        });                

        //Texto da pesquisa
        var table = $('#tabela').DataTable();
        table.search( 'mercado' ).draw(); 

        $("a[name^=teste]").on("click", function()
        {
            var nP = $("#tabela_paginate").find("ul");
            nP = nP.find('.active > a').text();
            console.info(nP);

            var nrRegistros = $("#tabela_length").find("select");
            console.info(nrRegistros.val());

            var search = $("#tabela_filter").find("input");
            var _href = $(this).attr('url');
            _href+= '/nLin/'+nrRegistros.val()+'/src/'+search.val()+'/pag/'+nP;
            //$('#'+$(this).attr('id')).attr("href",_href);
            //$('#'+$(this).attr('id')).trigger('click');
            var _id = $(this).attr('id');

            console.info(search.val());

            $("#"+_id).attr('href',_href);
            console.info($(this).attr('id'));
        });        
    });


        
    
       
</script>

<script>
    $('#confirm-delete').on('show.bs.modal', function(e) {
        $(this).find('.btn-ok').attr('href', $(e.relatedTarget).data('href'));        
    });
</script>