<!DOCTYPE html>
<html lang="pt">
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="Exemplo utilizando MVC e Templates em PHP">
    <meta name="author" content="JEAN FABIO FUCHS">

    <title>Teste</title>

    <link href="{PATH_PUBLIC}sb/bower_components/bootstrap/dist/css/bootstrap.min.css" rel="stylesheet">
    <link href="{PATH_PUBLIC}sb/bower_components/metisMenu/dist/metisMenu.min.css" rel="stylesheet">
    <link href="{PATH_PUBLIC}sb/dist/css/sb-admin-2.css" rel="stylesheet">
    <link href="{PATH_PUBLIC}sb/bower_components/font-awesome/css/font-awesome.min.css" rel="stylesheet" type="text/css">
    <link href="{PATH_PUBLIC}css/style2.css" rel="stylesheet" type="text/css">

    <script src="{PATH_PUBLIC}sb/bower_components/jquery/dist/jquery.min.js"></script>

    <script src="{PATH}jff.js"></script>
</head>
<body>
    <div id="wrapper">
        <!-- Navigation -->
        <nav class="navbar navbar-default navbar-static-top" role="navigation" style="margin-bottom: 0">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a class="navbar-brand" href="{PATH}"><i class="fa fa-home"></i> HOME</a>
            </div>

            <ul class="nav navbar-nav">
                <li class="dropdown">
                    <a class="dropdown-toggle" data-toggle="dropdown" href="#"> Cadastros
                        <i class="fa fa-caret-down"></i>
                    </a>
                    <ul class="dropdown-menu">
                        <li><a href="#"></i>Fornecedores</a></li>
                        <li><a href="#"></i>Cidades</a></li>
                        <li class="divider"></li>
                        <li><a href="#"></i>Usuários</a></li>
                        </li>
                    </ul>
                </li>

                <li class="dropdown">
                    <a class="dropdown-toggle" data-toggle="dropdown" href="#"> Movimentações
                        <i class="fa fa-caret-down"></i>
                    </a>
                    <ul class="dropdown-menu">
                        <li><a href="#"></i>Fornecedores</a></li>
                        <li><a href="#"></i>Cidades</a></li>
                        <li class="divider"></li>
                        <li><a href="#"></i>Usuários</a></li>
                        </li>
                    </ul>
                </li>

                <li class="dropdown">
                    <a class="dropdown-toggle" data-toggle="dropdown" href="#"> Relatórios
                        <i class="fa fa-caret-down"></i>
                    </a>
                    <ul class="dropdown-menu">
                        <li><a href="#"></i>Fornecedores</a></li>
                        <li><a href="#"></i>Cidades</a></li>
                        <li class="divider"></li>
                        <li><a href="#"></i>Usuários</a></li>
                        </li>
                    </ul>
                </li>
            </ul>

            <ul class="nav navbar-top-links navbar-right">
                <!-- Usuário -->
                <li class="dropdown">
                    <a class="dropdown-toggle" data-toggle="dropdown" href="#"> {USU_APELIDO}
                        <i class="fa fa-user fa-fw"></i>  <i class="fa fa-caret-down"></i>
                    </a>
                    <ul class="dropdown-menu dropdown-user">
                        <li><a href="{PATH}usuario/editar/id/{USU_ID}">
                            <i class="fa fa-user fa-fw"></i> Perfil do Usuário</a>
                        </li>
                        <li><a href="#"><i class="fa fa-gear fa-fw"></i> Configurações</a>
                        </li>
                        <li class="divider"></li>
                        <li><a href="{PATH}login/out"><i class="fa fa-sign-out fa-fw"></i> Sair</a>
                        </li>
                    </ul>
                </li>
            </ul>

            <!-- Menu lateral -->
            <div class="navbar-default sidebar" role="navigation">
                <div id="sidebarPage" class="sidebar-nav navbar-collapse collapse">
                    <ul class="nav" id="side-menu">
                        <li class="sidebar-search">
                            <div class="input-group custom-search-form">
                                <input type="text" class="form-control" id="mainSearch" placeholder="Search...">
                                <span class="input-group-btn">
                                    <button class="btn btn-default" type="button">
                                        <i class="fa fa-search"></i>
                                    </button>
                                </span>
                            </div>
                        </li>

                        {MENUS}
                    </ul>
                </div>
                <!-- /.sidebar-collapse -->
            </div>
        </nav>
        <div id="page-wrapper">
            {PAGE_CONTENT}
        </div>
    </div>

    <script src="{PATH_PUBLIC}sb/bower_components/bootstrap/dist/js/bootstrap.min.js"></script>
    <script src="{PATH_PUBLIC}sb/bower_components/metisMenu/dist/metisMenu.min.js"></script>
    <script src="{PATH_PUBLIC}sb/dist/js/sb-admin-2.js"></script>
</body>
</html>
