<div class="container-fluid">
    <div class="row">
        <h1 class="page-header">
            ERRO 404
        </h1>

        <div class="jumbotron">
            <h1>Página não encontrada!</h1>

            <?php
                $msgErro = Session::get('msgErro');
                foreach ($msgErro as $msg) {
                    echo "<p>".$msg."</p>";
                }
            ?>
            <p>Por favor, entre em contato com o administrador do sistema.</p>

            <a href="<?php echo PATH; ?>" class="btn btn-large btn-info">
                <i class="icon-home icon-white"></i>HOME</a>
        </div>
    </div>
</div>