<script type="text/javascript">
    jQuery(function($){
        $("#Celular").mask("(99) 9999-9999");
    });
</script>

<body>
    <div id="wrapper">
        <div id="page-wrapper">
            <div class="container-fluid">

                <!-- Page Heading -->
                <div class="row">
                    <div class="col-lg-12">                        

                        <h1 class="page-header">
                            Fornecedor
                            <small>Edição</small>                            
                        </h1>    
                    
                        <?php echo Alert::render(); ?>

                        <?php echo HtmlUtils::MontarBreadCrumbs('Editar', 'Fornecedores', $view_linkCancelar, $view_get["ID"]); ?>
                    
                        <form action="/TESTE/fornecedores/gravar" id="reservationForm" role="form" method="post">
                            <div class="form-group">
                                <label for="Nome">Nome do Fornecedor</label>
                                <input type="text" name="RegForm[Nome]" class="form-control" id="Nome" required
                                       value="<?php echo $view_get["Nome"]; ?>">
                            </div>

                            <div class="form-group">
                                <label for="Celular">Celular</label>
                                <input type="text" name="RegForm[Celular]" class="form-control" id="Celular"       required value="<?php echo $view_get["Celular"]; ?>">
                            </div>
                                
                            <div>
                                <input type="hidden" name="RegForm[ID]" value="<?php echo $view_get["ID"]; ?>">
                                <input type="hidden" name="acao" value="<?php echo $view_acao; ?>" />
                                <input class="btn btn-default" type="reset" value="Limpar" />
                                <input class="btn btn-success" type="submit" value="Salvar">
                                <a class="btn btn-warning" href="<?php echo $view_linkCancelar; ?>">Cancelar</a>
                            </div>
                        </form>
                    </div>
                </div>                       
            </div>            
        </div>
    </div>
</div>