<div id="page-wrapper">
    <div class="container-fluid">
        <div class="row">
            <div class="col-lg-12">
                <h1 class="page-header">Bem Vindo
                    <strong><?php echo Session::getFrom('Login','Apelido'); ?></strong>.
                    <small> <br />Tenha um dia bem "humor delícia"!</small>
                </h1>
            </div>
        </div>
    </div>
</div>
