<?php  	
    ob_start();

	function activeMenu($menu) {
        $aux = isset($_GET) ? implode("/", $_GET) : "";
        return (strpos($aux, $menu) === 0) ? 'class="active"' : NULL;
    }

    $menus = [];
    $menus[] = array("fornecedores" => "Fornecedores");
    $menus[] = array("alunos" => "Alunos");
?>    

<!DOCTYPE html>
<html lang="pt-BR">
<head>
	<meta charset="UTF-8">
	<meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="Exemplo utilizando MVC e Templates em PHP">
    <meta name="author" content="JEAN FABIO FUCHS">
	<title>Teste</title>
    <link href="//maxcdn.bootstrapcdn.com/bootstrap/3.3.2/css/bootstrap.min.css" rel="stylesheet">
	<!--link href="<?php echo PATH_PUBLIC; ?>css/sb-admin/css/bootstrap.min.css" rel="stylesheet"-->
    <link href="<?php echo PATH_PUBLIC; ?>css/sb-admin/css/sb-admin.css" rel="stylesheet">
    <link href="<?php echo PATH_PUBLIC; ?>css/sb-admin/font-awesome/css/font-awesome.min.css" rel="stylesheet" type="text/css">  
    <link href="<?php echo PATH_PUBLIC; ?>js/tablesorter/themes/blue/style2.css" rel="stylesheet" type="text/css">
</head>

<body>
    <div id="wrapper"> 
        <nav class="navbar navbar-inverse navbar-fixed-top" role="navigation">

            <!-- Brand and toggle get grouped for better mobile display -->
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-ex1-collapse">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a class="navbar-brand" href="<?php echo PATH; ?>">HOME</a>
            </div>

            <!-- Top Menu Items -->
            <ul class="nav navbar-right top-nav">             
                <li class="dropdown">
                    <a href="#" class="dropdown-toggle" data-toggle="dropdown"><i class="fa fa-user"></i>
                        <?php echo $_SESSION['UsuarioNome']; ?><b class="caret"></b></a>
                    <ul class="dropdown-menu">
                        <li><a href="formulario.php?id=<?php echo $_SESSION['UsuarioID']; ?>">
                            <i class="fa fa-fw fa-user"></i> Cadastro</a></li>
                        <li><a href="#"><i class="fa fa-fw fa-envelope"></i> Inbox</a></li>
                        <li><a href="#"><i class="fa fa-fw fa-gear"></i> Configurações</a></li>
                        <li class="divider"></li>
                        <li><a href="banco_alunos.php?acao=sair"><i class="fa fa-fw fa-power-off"></i> Sair</a></li>
                    </ul>
                </li>                
            </ul>

            <!-- Sidebar Menu Items - These collapse to the responsive navigation menu on small screens -->
            <div class="collapse navbar-collapse navbar-ex1-collapse">
                <ul class="nav navbar-nav side-nav">
                    <?php echo HtmlUtils::MontarMenus($menus); ?>                    
                </ul>
            </div>            
        </nav>
    </div> 
      
    <!-- jQuery -->    
    <script src="<?php echo PATH_PUBLIC; ?>js/jquery-2.1.3.min.js"></script>
    <script src="<?php echo PATH_PUBLIC; ?>js/tablesorter/jquery.tablesorter.min.js" type="text/javascript"></script>
    <script src="<?php echo PATH_PUBLIC; ?>css/sb-admin/js/bootstrap.min.js"></script>
    <script src="<?php echo PATH_PUBLIC; ?>js/jquery.maskedinput.js"></script>
</body>
</html>